### ISSUE TITLE
.sh script gives permission denied

### ISSUE THREAD

**Issue by mkkannan** [SAP/devops-docker-xs-cli#8]
Hi ,

I am trying to use this docker image in the gitlab pipeline and trying to run a shell script. It says permission denied. 
I see it use PIPER user and when I do chmod +x script.sh file it says Operation not permitted.

How do I run the Shell script inside this docker image? Kindly suggest

Thanks

**Comment by the1Prince** [comment]
This worked for me:
1. Add this line to your Dockerfile to grant permission RUN chmod +x <directory/to your/sh file>
2. Add this line at the top of your sh file #!/bin/bash

**Comment by kaylinche** [comment]
Will close that issue, because seems outdated.
